name: Testisivusto
favicon: null
layout_spectrum: 0.8892883055377752
typography_spectrum: 0.9203405964653939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.508617429761216
  lightness: 0.013265739660710096
  saturation: 0.4397517112083733
  rhythmicContrast: 0.4283141577616334
purpose: []
