typography_spectrum: 0
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0
  lightness: 0.013265739660710096
  saturation: 0.1875
  rhythmicContrast: 0.4283141577616334
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Testisivusto
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Reunus == Weikko Digital
purpose: []
